# -*- coding: utf-8 -*-
"""Desafio ML - detecção de fraude bancárias com comentários.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15G-eIPP2q06vmQIctIbYuMK_zn0eVCWc

Detecção de fraudes em transações bancárias
"""

# importando o dataset de API, disponível utilizada para exercício.
# variável class é a mais importante, em que 0 a transacao não é fraudulenta, e 1 indica fraude.
# preparar para começar a analisar padrões de comportamento.
import pandas as pd
url = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"
df = pd.read_csv(url)
df.head()

"""Problema de classificação desbalanceada"""

# Um dos pontos mais importantes da detecção de fraude
# Calculando a proporção de cada tipo de transação
# Interpretação = dataset desbalanceado, tem mais de um tipo de fraude do que a outra
# Pode ensinar o modelo a aprender errado --> acaba levando a baixa acurácia
# para que o modelo não seja inútil --> quero que ele acerte a classe rara (fraude), pois é a mais perigosa caso não seja detectada.
df["Class"].value_counts(normalize=True)

"""Feature engineering"""

# Podemos criar novas variaveis que nos ajudem a interpretar melhor com o modelo, transformar os dados brutos em informações úteis para o modelo
# É necessário porque o modelo não aprende o contexto
# Foi usado transformação logarítmica, que é para comprimir valores = valores muito grandes diminuem em escala, valores pequenos são menos afetados
# Para evitar problemas com valores iguais a zero, pois em dados financeiros é normal ter valores muito discrepantes e atrapalhar o aprendizado do modelo
import numpy as np
df["Amount_log"] = np.log1p(df["Amount"])

# Padronização dos dados
# Valores diferentes ficam na mesma escala, independente do tamanho original, passando a ser comparáveis
# O fit vai calcular a média e o DP da coluna amount
# o Transform aplica a transformação aos valores e mostra na coluna amount scaled
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df["Amount_scaled"] = scaler.fit_transform(df[["Amount"]])

# Preparar os dados para treinar o modelo
# Separo as variáveis em x e y
# x representa as features = todas as variáveis de entrada
# y represent o target = o que estamos buscando analisar se é fraude ou não
from sklearn.model_selection import train_test_split
x = df.drop("Class", axis=1)
y = df["Class"]

#separando os dados em conjuntos de teste e treino, porque o conjunto de treino é usado para ensinar o modelo, e o conjunto de teste é usado para avaliar o modelo depois
# test size = 0.3 significa que 70% dos dados foram usados para treinar o modelo e 30% dos dados foram usados para o teste posteriormente
# random_state = 42 serve para garantir que a divisão seja sempre a mesma, para melhor reprodutibilidade
# stratify=y garante que a proporção de fraudes e não fraudes seja mantida, tanto no treino quanto no teste, caso contrario poderia mostrar um conjunto de dados com pouca ou nenhuma fraude uma vez que o dataset é desbalanceado
x_train, x_test, y_train, y_test = train_test_split(
    x, y, stratify=y, test_size=0.3, random_state=42
)

"""Avaliação dos modelos/Modelagem de dados

Regressão logística
"""

# O modelo de regressão logística é um modelo de classificação, objetivo é prever categorias, nesse caso, se é fraude (classe 0) ou não (classe 1)
# max_iter de 1000 são quantas iterações ele vai convergir
# modelo aprende padrões a partir dos dados de treino com o model.fit
# no modelo model.predict ele vai avaliar oss 30% de dados (dados do conjunto teste) para avaliar se tem fraude
# o aviso gerado é porque chegou no máximo de iterações permitido, o que pode ser resolvido aumentando a quantidade de iterações
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

# para ver as métricas mais importantes para as classificações --> avaliando como o modelo desempenhou
# foco na classe 1 porque é a classe que mostra as fraudes
# A precisão de 0.84 indica que entre todas as transações, o modelo identificou que 84% delas eram fraude.
# A recall de 0.66 indica que o modelo conseguiu identificar 66% das fraudes reais, o que precupa pois ele está deixando de detectar 34% das fraudes reais.
# o F1-score dá uma visão geral da qualidade do modelo, mostrando o equilíbrio entre acurácia e recall.
# o fato de o modelo ter um f1-score de 1 significa que ele ficou viciado, detectando todas as transacoes de classe 0, mas que não representa um bom resultado pra sua capacidade de detectar as fraudes.
# Por isso, é melhor olhar o recall do que o valor da acurácia, ou seja se as verdadeiras fraudes foram detectadas.
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

# Curva ROC mostra o desempenho do modelo em diferentes limiares de decisão
# True Positive Rate mostra o mesmo que o recall, ou o quantas fraudes o modelo conseguiu identificar
# False Positive Rate mostra quantas transações normais foram classificadas como fraude
# Cada ponto representa um limite diferente da decisão do modelo, para analisar o comportamento geral
# Quanto mais próximo do canto superior esquerdo, melhor o modelo = alto recall e baixo erro
# Se a curva for uma diagonal reta, o modelo seria aleatório, sem capacidade de distinguir fraude e não fraude.
# valor da área abaixo da curva (AUC) indica um valor proximo de 1 e um modelo muito bom, 0.5 seria um modelo aleatório.
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_probs = model.predict_proba(x_test)[:,1]

fpr, tpr, _ =  roc_curve(y_test, y_probs)

plt.plot(fpr, tpr)
plt.title("ROC Curve relationship between true and false positive rate")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()
print("AUC:", roc_auc_score(y_test, y_probs))

# Importante observar o tradeoff entre as duas métricas
# Quanto mais aumenta o recall, a precision diminui, e vice versa
# No início, o modelo é mais conservador porque a precision estava em 1, ou seja, só aponta fraude quanto tem muita certeza
# À medida que o recall aumenta, o modelo passa a identificar mais fraudes
# Porém, o precision cai, o que aumenta os falsos positivos
# No final, quando o recall está alto e a precision muito baixa, significa que o modelo está marcando muitas transações como fraude, incluindo as que não são
# Em problemas desbalanceados, mostra um melhor modelo do que a curva ROC por si só
from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(y_test, y_probs)

plt.plot(recall, precision)
plt.title("Precision Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

"""Balanceamento de dados (Técnica Undersampling escolhida)"""

# Undersampling = Pegar todas as fraudes e utiliza a mesma quantidade de transações usando o sample
# Reduz a classe majoritária (classe 0) para ficar do mesmo tamanho da classe minoritária (classe 1)
# Risco é de perder muitos dados normais, perder a qualidade geral dos dados
fraudes = df[df["Class"] == 1]
normais = df[df["Class"] == 0].sample(len(fraudes), random_state=42)

df_under = pd.concat([fraudes, normais])

# Modelo baseado em árvores de decisão, tende a ser mais preciso do que a regressão logística
# Aqui, o modelo já consegue detectar 76% das fraudes, e o f1-score também aumentou, agora estando em 0.79
#
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    class_weight="balanced",
    n_jobs= -1,
    random_state=42
)

rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)

print(classification_report(y_test, y_pred_rf))

# Pipeline serve para organizar o fluxo de processamento em 2 etapas
# O standard scaler e a regressão logística, tudo em um único fluxo, o que diminui o risco de erros e garante mais consistência
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

# Ajuste do limite para 0.3 (por padrão é 0.5) significa ter mais rigor com a fraude, ser capaz de detectar mais as fraudes
# Só com a regressão logística estava em 0.69, com o ajuste do threshold aumentou para 0.71.
threshold = 0.3

y_pred_custom = (y_probs > threshold).astype(int)

print(classification_report(y_test, y_pred_custom))

"""Modelo Avançado - XGBoost"""

# Modelo mais avançado e baseado em boosting --> técnica de modelos simples, geralmente árvores, em que cada modelo tenta corrigir os modelos anteriores, garantindo um aprendizado sequencial
# Cada árvore utiliza do aprendizado da árvore anterior, diferente do randomforest em que as árvores são independentes
# Muito utilizado e mais poderoso, útil em aplicações reais, como para detectar fraudes
from xgboost import XGBClassifier

xgb = XGBClassifier(
    scale_pos_weight=10,
    use_label_encoder=False,
    eval_metric="logloss"
)

xgb.fit(x_train, y_train)

y_pred_xgb = xgb.predict(x_test)

# A precision ficou em 0.93, ou seja, quando o modelo diz que é fraude, ele acertou em 93% dos casos
# O recall fiocu em 0.78, ou seja, em 78% das fraudes.
# O F1-score é 85%, um bom equilíbrio entre precision e recall.
print(classification_report(y_test, y_pred_xgb))

"""Importância das Variáveis"""

# No eixo horizontal, temos as variáveis de 1 a 28
# No eixo vertical, temos o peso de cada variável no modelo
# Algumas variáveis vão ter um peso maior que outras no padrão de aprendizagem do modelo
# Mesmo sendo um modelo complexo, ajuda a focar e selecionar as variáveis mais importantes
# Ajuda no entendimento do modelo do negócio, mostrando o que essa variável representa e como ela se relaciona com a fraude.
import matplotlib.pyplot as plt

importancias = xgb.feature_importances_

plt.bar(range(len(importancias)), importancias)
plt.title("Importância das variáveis")
plt.show()

"""Ajuste de hiperparêmetros"""

# Testa várias combinações de parâmetros automaticamente
# São parâmetros que não são aprendidos pelo modelo, mas que precisam ser definidos por nós
# O Grid vai testar todas as combinações possíveis entre esses fatores, e avaliar qual o melhor, nesse caso o melhor é o recall - por isso foi definido como o melhor abaixo.
from sklearn.model_selection import GridSearchCV

param_grid = {
    "max_depth": [3, 5],
    "n_estimators": [50, 100]
}

grid = GridSearchCV(
    XGBClassifier(eval_metric="logloss"),
    param_grid,
    scoring="recall",
    cv=3
)

grid.fit(x_train, y_train)

print("Melhor modelo:", grid.best_params_)

"""Explicabilidade (SHAP)"""

# SHAP é uma técnica que explica quanto cada variável vai impactar o modelo, por consequente, na decisão
# o mean shap value é a média de impacto de cada variável --> quanto maior o valor, mais essa variável vai impactar
# A V4 e a V14 são as duas variáveis que mais impactam, as mais importantes.
# Permite entender o modelo, mesmo em cenários complexos como no caso de fraudes --> importante para confiança, auditoria e tomada de decisão.
import shap
explainer = shap.Explainer(xgb)
shap_values = explainer(x_test[:100])

shap.plots.bar(shap_values)

# outras formas de observar em gráficos diferentes do de barras mencionados em aula pela profa. Isadora
# as variáveis v4 e v14 continuam sendo visivelmente as que mais impactaram o modelo e sua tomada de decisão em detectar fraude
import shap
explainer = shap.Explainer(xgb)
shap_values = explainer(x_test[:100])

shap.plots.beeswarm(shap_values)

# outro modelo de gráfico com a técnica SHAP, ainda em v4 e v14 pode-se observar maior quantidades de pontos
import shap
explainer = shap.Explainer(xgb)
shap_values = explainer(x_test[:100])

shap.plots.scatter(shap_values)

# outro modelo de gráfico em violino, achei interessante pela diferença em espessura e cores representando maiores impactos nessas duas variáveis
import shap
explainer = shap.Explainer(xgb)
shap_values = explainer(x_test[:100])

shap.plots.violin(shap_values)